mode: predict
debug: False
load_ckpt: experiments/vm/checkpoint_20260519_084730/checkpoint_best.pkl  # 首次使用请替换 <run_name> 为实际的运行目录

components:
  data: predict
  transform: predict
  system: vm
  model: vm

writer:
  __target__: vm
  save_dir: results
  save_name: denoised