mode: train
debug: False
load_ckpt: experiments/vm/checkpoint_20260519_084730/checkpoint_best.pkl  # uncomment to resume from previous best

components:
  data: train
  transform: vm
  system: vm
  model: vm

loss:
  loss: 1.0

optimizer:
  __target__: adam
  lr: 0.0001

trainer:
  epochs: 100
  run_name: ""
  # patience: 10       # uncomment to enable early stopping (stop if no improvement for N epochs)
  scheduler:
    type: step
    step_size: 30
    gamma: 0.1